from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from core.artist_presets import get_artist_preset
from core.instrument_tag_normalizer import normalize_lyrics_tags
from core.project_io import safe_name
from core.version import build_label


ROOT = Path(__file__).resolve().parents[1]


def _project_folder(project_name: str, base_dir: str | Path | None = None) -> Path:
    root = Path(base_dir) if base_dir else ROOT / "project_data" / "projects"
    return root / safe_name(project_name or "project")


def _selected_hook(song: Dict[str, Any]) -> Dict[str, Any]:
    hook = song.get("selected_hook")
    if isinstance(hook, dict):
        return hook
    return {"hook_text": song.get("selected_hook_text") or str(hook or "")}


def _setting_value(settings: Dict[str, Any], key: str) -> Any:
    value = settings.get(key, "")
    if isinstance(value, str):
        return value
    return str(value)


def build_suno_full_package(song: Dict[str, Any], project_name: str = "") -> str:
    preset = get_artist_preset(song.get("artist_preset", "vela_moon"))
    hook = _selected_hook(song)
    settings = song.get("advanced_settings", {}) or {}
    lyrics = song.get("normalized_song_output") or normalize_lyrics_tags(song.get("complete_lyrics", ""), preset)
    return "\n".join([
        "--------------------------------",
        "Song Title:",
        str(song.get("title") or project_name or "Untitled Song"),
        "",
        "Artist Preset:",
        str(song.get("artist_preset") or preset.get("artist_id", "vela_moon")),
        "",
        "Music Style Prompt:",
        str(song.get("music_style_prompt", "")),
        "",
        "Weirdness:",
        str(song.get("weirdness") or _setting_value(settings, "weirdness")),
        "",
        "Style Influence:",
        str(song.get("style_influence") or _setting_value(settings, "style_influence")),
        "",
        "--------------------------------",
        "Complete Lyrics with Tags",
        "--------------------------------",
        "",
        lyrics,
        "",
        "--------------------------------",
        "Hook Information",
        "--------------------------------",
        "",
        "Selected Hook:",
        str(hook.get("hook_text", "")),
        "",
        "Hook Scores:",
        f"- Emotional: {hook.get('emotional_score', '')}",
        f"- Catchy: {hook.get('catchy_score', '')}",
        f"- TikTok: {hook.get('tiktok_potential', '')}",
        "",
        "--------------------------------",
        "Generated By",
        "--------------------------------",
        build_label(),
        "",
    ])


def export_suno_files(
    project_name: str,
    song: Dict[str, Any],
    base_dir: str | Path | None = None,
) -> Dict[str, Any]:
    try:
        folder = _project_folder(project_name, base_dir) / "exports"
        folder.mkdir(parents=True, exist_ok=True)
        preset = get_artist_preset(song.get("artist_preset", "vela_moon"))
        lyrics = song.get("normalized_song_output") or normalize_lyrics_tags(song.get("complete_lyrics", ""), preset)
        full_path = folder / "suno_full_package.txt"
        lyrics_path = folder / "lyrics_only.txt"
        full_path.write_text(build_suno_full_package(song, project_name), encoding="utf-8")
        lyrics_path.write_text(lyrics, encoding="utf-8")
        return {
            "ok": True,
            "message": "Suno exports created",
            "data": {
                "exports_dir": str(folder),
                "suno_full_package": str(full_path),
                "lyrics_only": str(lyrics_path),
                "suno_full_text": full_path.read_text(encoding="utf-8"),
                "lyrics_only_text": lyrics,
            },
            "error": "",
        }
    except Exception as exc:
        return {"ok": False, "message": "Suno export failed", "data": {}, "error": str(exc)}
